# This is a basic workflow to help you get started with Actions

name: Publish Assignments to SNS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Publish Changes to SNS
        # You may pin to the exact commit or the version.
        # uses: nothingalike/sns-publish-topic@200ba6a86ee81659f183a03d7f92f2ae5734b493
        uses: nothingalike/sns-publish-topic@v1.6
        with:
          # The message you want to send
          MESSAGE: changed
          # The topic arn you are sending
          TOPIC_ARN: ${{ secrets.TOPIC_ARN }}
          # A AWSN SNS Region. Can alternatively be stored in environment
          AWS_REGION: us-west-2
          # A AWS SNS Key. Can alternatively be stored in environment
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # A AWS SNS Secret. Can alternatively be stored in environment
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
